### ISSUE TITLE
Fix cache key

### ISSUE THREAD

**Issue by eamsen** [mozilla/node-janus#17]
The current caching key isn't adequate for most real-world scenarios, it needs to include following elements
- UA
- `accept-encoding` headers for xz support
- query

**Comment by snorp** [comment]
Including the full UA string might not be what we want, and would probably drastically reduce our hit rate. We probably at least want to include the firefox/webkit/IE/whatever part though.

It's worth looking at what other caches do here for sure. Let's not reinvent the wheel too much.

**Comment by eamsen** [comment]
https://github.com/mozilla/node-janus/pull/42
