### ISSUE TITLE
Resources fail to load

### ISSUE THREAD

**Issue by gcp** [mozilla/node-janus#21]
http://vimeo.com/44339328

Video controls aren't displayed with Janus enabled. Works fine otherwise.

**Comment by eamsen** [comment]
@gcp Can you still reproduce it? Controls load fine for me.

**Comment by eamsen** [comment]
Reproducing only with `gif2video` enabled, getting following browser security error in this case:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://player.vimeo.com/video/44339328/config?autoplay=0&amp;byline=0&amp;bypass_privacy=1&amp;context=clip.main&amp;default_to_hd=1&amp;portrait=0&amp;title=0&amp;s=6f444e402272bbb0b045ee68e55fc7b7b426ae1e. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by Ackar** [comment]
This is caused by an incorrect handling of encoding/decoding in cheerio. For example `&amp;` is changed to `&amp;amp;`.
This is fixed in the last version of cheerio.
