### ISSUE TITLE
Incomplete pdf.js loading

### ISSUE THREAD

**Issue by eamsen** [mozilla/node-janus#39]
## STR
1. Install and active PDF Viewer (pdf.js).
2. Activate Proxy.
3. Open [some big PDF file](http://www.cs.utexas.edu/users/EWD/ewd03xx/EWD340.PDF).
### Expected

PDF is loaded and viewed.
### Actual

PDF is only partially loaded (about 300 KB).

**Comment by snorp** [comment]
Yeah, can confirm this one here too. Weird.

**Comment by snorp** [comment]
It looks like PDF.js makes Range requests for chunks of the document. The cache does not include that as part of the key, so we return erroneously cached results. I think the PDF.js parser just gives up after that, not sure.

**Comment by eamsen** [comment]
Fixed with https://github.com/mozilla/node-janus/pull/42
