### ISSUE TITLE
Janus breaks sites on local network or local machine

### ISSUE THREAD

**Issue by eamsen** [mozilla/node-janus#41]
The Janus addon breaks URLs like "http://fossology/". My /etc/hosts says, among other things:

127.0.0.1 fossology

However, with the proxy enabled, that URL doesn't work.

[Originally reported](https://github.com/mozilla/janus-addon/issues/1) by @gerv.

**Comment by gerv** [comment]
How could this be an issue with the proxy itself? The proxy doesn't have access to my local "hosts" file. Surely it's about making sure Firefox is configured correctly to pass DNS requests for local network resources to my normal DNS provider rather than doing whatever the proxy does with them?

Gerv

**Comment by eamsen** [comment]
You're right about the proxy not having access to your local `hosts` file, however, the proxy provides the PAC, which dictates your browser's behavior when resolving host names.

We should think about accepting a generic local host domain (e.g., `.local`), which forces direct connection and therefore would consider your local host configuration. For this you would have to add the domain suffix to all your local host entries.

Another option is to ignore all plain host names, like in your example.

In the meanwhile, you could provide your own PAC file based on the same ideas and configure the add-on to use it instead, for example:

```
function FindProxyForURL(url, host) {
  if (isPlainHostName(host) ||
      dnsDomainIs(host, ".local") ||
      url.substring(0, 6) == "https:") {
    return "DIRECT";
  }
  return "HTTPS janus.allizom.org:44300";
}
```

**Comment by gerv** [comment]
You should certainly ignore all plain host names. ICANN has disallowed A records at the top level (yay!), so plain hostnames are guaranteed to be local.

Then, ideally, you would also return DIRECT for any domain name which did not end in a TLD from ICANN's root zone TLD list. If you have access to the Public Suffix List from the PAC file, or could add an API to do so, that might be an acceptable substitute as the PSL is a superset of the root zone list. 

Gerv
