### ISSUE TITLE
Firefox repeatedly crashes and internet is slower than ever

### ISSUE THREAD

**Issue by ghost** [mozilla/node-janus#69]
After installing this addon, firefox on my pc crashed 32 times in a single day. And also my internet connection speed reduced to half. Then I disabled Janus and everything went back to normal. I tried it once more and the same problems appeared once again.

**Comment by eamsen** [comment]
There was an issue with OCSP in previous Firefox versions, which caused crashes (generally) and slowdowns (for HTTPS sites) with the proxy enabled.

Which version of Firefox and which operating system are you running on?

**Comment by ghost** [comment]
I am using firefox 33.0.3 and running windows 8 Pro. I have tried to update firefox to the latest version but failed because it crashes everytime tried.

**Comment by eamsen** [comment]
You can try disabling OCSP to see if that's the known issue. To do so, go to the URL `about:config`, search for `OCSP` and set `security.OCSP.enabled` to `0`.

Alternatively, you can try a newer Firefox build, for example [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/).

**Comment by ghost** [comment]
Thanks for the solution, firefox stopped crashing after disabling OCSP. But internet is still extremely slow in firefox. Please give me a solution to solve the slow internet speed issue.

**Comment by eamsen** [comment]
There are a few things that could cause increased response times when using the proxy:
- you're on a fast (WiFi/Ethernet) connection, with high bandwidth
- your location, the proxy test instance is located in the US, you might experience long round trip times when using the proxy from anywhere else
- you're on a high bandwidth, high latency (to the proxy) connection

In general, the proxy does add a delay (currently about 200ms on average) per request, but at the same time it reduces the amount of data you download, so you should profit from it the most on low bandwidth connections.

How bad are the slowdowns for you? Can you visit a specific page, for example http://www.google.com/nexus/ (make sure it's http), hit `shift``control``i`, disable caching via the 
Toolbox Options and reload a couple of times with the proxy enabled and then some more with the proxy disabled and then note the average load times (bottom right) in comparison?

**Comment by ghost** [comment]
On the latest version of janus, the data savings is extremely low compared to previous times. And I am also experiencing extremely low internet speeds. I stay in Bangladesh and use 1Mbps internet limited connection.
